name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "flask-application-package"
  EB_APPLICATION_NAME       : "spring-petclinic-angular-frontend"
  EB_ENVIRONMENT_NAME       : "SpringPetclinicAngularFrontend-env"
  DEPLOY_PACKAGE_NAME:      : "flask_app_${{ github.sha }}.zip
  AWS_REGION_NAME           : "eu-west-3"
  
on:
  push:
    branches:
      - master
   
jobs:
  ci_part:
    runs-on: ubuntu-latest

   
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v2
      
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

