name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "elasticbeanstalk-us-west-2-836380706446"
  EB_APPLICATION_NAME       : "spring-petclinic-angular-frontend"
  EB_ENVIRONMENT_NAME       : "SpringPetclinicAngularFrontend-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-west-2"
  
on:
  push:
    branches:
      - master
   
jobs:
  ci_part:
    runs-on: ubuntu-latest

   
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v2
      
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

    - name: Configure my AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     : ${{ secrets.my-aws-access }}
        aws-secret-access-key : ${{ secrets.my-aws-secret-access-key }}
        aws-region            : ${{ env.AWS_REGION_NAME }}
        
    - name: Copy deployment package to S3 backet
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }}  s3://${{env.EB_PACKAGE_S3_BUCKET_NAME}}/
